/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlockedRouteImport } from './routes/blocked'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RequestDemoRouteImport } from './routes/request-demo'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedDoctorRouteRouteImport } from './routes/_authenticated/doctor/route'
import { Route as AuthenticatedMmRouteRouteImport } from './routes/_authenticated/mm/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAnalysesRouteImport } from './routes/_authenticated/admin/analyses'
import { Route as AuthenticatedAdminAssessmentsRouteImport } from './routes/_authenticated/admin/assessments'
import { Route as AuthenticatedAdminExportRouteImport } from './routes/_authenticated/admin/export'
import { Route as AuthenticatedAdminManagersRouteImport } from './routes/_authenticated/admin/managers'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminValidationsRouteImport } from './routes/_authenticated/admin/validations'
import { Route as AuthenticatedDoctorIndexRouteImport } from './routes/_authenticated/doctor/index'
import { Route as AuthenticatedDoctorDownloadRouteImport } from './routes/_authenticated/doctor/download'
import { Route as AuthenticatedDoctorHistoryRouteImport } from './routes/_authenticated/doctor/history'
import { Route as AuthenticatedDoctorNewRouteImport } from './routes/_authenticated/doctor/new'
import { Route as AuthenticatedDoctorProfileRouteImport } from './routes/_authenticated/doctor/profile'
import { Route as AuthenticatedMmIndexRouteImport } from './routes/_authenticated/mm/index'
import { Route as AuthenticatedMmAnalyticsRouteImport } from './routes/_authenticated/mm/analytics'
import { Route as AuthenticatedMmDoctorsRouteImport } from './routes/_authenticated/mm/doctors'
import { Route as AuthenticatedMmUsageRouteImport } from './routes/_authenticated/mm/usage'
import { Route as ApiPublicDemoSetupRouteImport } from './routes/api/public/demo-setup'
import { Route as AuthenticatedAdminCompaniesIndexRouteImport } from './routes/_authenticated/admin/companies.index'
import { Route as AuthenticatedAdminCompaniesIdRouteImport } from './routes/_authenticated/admin/companies.$id'
import { Route as AuthenticatedAdminDoctorsIndexRouteImport } from './routes/_authenticated/admin/doctors.index'
import { Route as AuthenticatedAdminDoctorsIdRouteImport } from './routes/_authenticated/admin/doctors.$id'
import { Route as AuthenticatedAdminReportsIndexRouteImport } from './routes/_authenticated/admin/reports.index'
import { Route as AuthenticatedAdminReportsIdRouteImport } from './routes/_authenticated/admin/reports.$id'
import { Route as AuthenticatedDoctorReportsIndexRouteImport } from './routes/_authenticated/doctor/reports.index'
import { Route as AuthenticatedDoctorReportsIdRouteImport } from './routes/_authenticated/doctor/reports.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockedRoute = BlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestDemoRoute = RequestDemoRouteImport.update({
  id: '/request-demo',
  path: '/request-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDoctorRouteRoute =
  AuthenticatedDoctorRouteRouteImport.update({
    id: '/doctor',
    path: '/doctor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMmRouteRoute = AuthenticatedMmRouteRouteImport.update({
  id: '/mm',
  path: '/mm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAnalysesRoute =
  AuthenticatedAdminAnalysesRouteImport.update({
    id: '/analyses',
    path: '/analyses',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAssessmentsRoute =
  AuthenticatedAdminAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminExportRoute =
  AuthenticatedAdminExportRouteImport.update({
    id: '/export',
    path: '/export',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminManagersRoute =
  AuthenticatedAdminManagersRouteImport.update({
    id: '/managers',
    path: '/managers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminValidationsRoute =
  AuthenticatedAdminValidationsRouteImport.update({
    id: '/validations',
    path: '/validations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedDoctorIndexRoute =
  AuthenticatedDoctorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDoctorRouteRoute,
  } as any)
const AuthenticatedDoctorDownloadRoute =
  AuthenticatedDoctorDownloadRouteImport.update({
    id: '/download',
    path: '/download',
    getParentRoute: () => AuthenticatedDoctorRouteRoute,
  } as any)
const AuthenticatedDoctorHistoryRoute =
  AuthenticatedDoctorHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedDoctorRouteRoute,
  } as any)
const AuthenticatedDoctorNewRoute = AuthenticatedDoctorNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedDoctorRouteRoute,
} as any)
const AuthenticatedDoctorProfileRoute =
  AuthenticatedDoctorProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDoctorRouteRoute,
  } as any)
const AuthenticatedMmIndexRoute = AuthenticatedMmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedMmRouteRoute,
} as any)
const AuthenticatedMmAnalyticsRoute =
  AuthenticatedMmAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedMmRouteRoute,
  } as any)
const AuthenticatedMmDoctorsRoute = AuthenticatedMmDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AuthenticatedMmRouteRoute,
} as any)
const AuthenticatedMmUsageRoute = AuthenticatedMmUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthenticatedMmRouteRoute,
} as any)
const ApiPublicDemoSetupRoute = ApiPublicDemoSetupRouteImport.update({
  id: '/api/public/demo-setup',
  path: '/api/public/demo-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminCompaniesIndexRoute =
  AuthenticatedAdminCompaniesIndexRouteImport.update({
    id: '/companies/',
    path: '/companies/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCompaniesIdRoute =
  AuthenticatedAdminCompaniesIdRouteImport.update({
    id: '/companies/$id',
    path: '/companies/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDoctorsIndexRoute =
  AuthenticatedAdminDoctorsIndexRouteImport.update({
    id: '/doctors/',
    path: '/doctors/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDoctorsIdRoute =
  AuthenticatedAdminDoctorsIdRouteImport.update({
    id: '/doctors/$id',
    path: '/doctors/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReportsIndexRoute =
  AuthenticatedAdminReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReportsIdRoute =
  AuthenticatedAdminReportsIdRouteImport.update({
    id: '/reports/$id',
    path: '/reports/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedDoctorReportsIndexRoute =
  AuthenticatedDoctorReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedDoctorRouteRoute,
  } as any)
const AuthenticatedDoctorReportsIdRoute =
  AuthenticatedDoctorReportsIdRouteImport.update({
    id: '/reports/$id',
    path: '/reports/$id',
    getParentRoute: () => AuthenticatedDoctorRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blocked': typeof BlockedRoute
  '/login': typeof LoginRoute
  '/request-demo': typeof RequestDemoRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/doctor': typeof AuthenticatedDoctorRouteRouteWithChildren
  '/mm': typeof AuthenticatedMmRouteRouteWithChildren
  '/admin/analyses': typeof AuthenticatedAdminAnalysesRoute
  '/admin/assessments': typeof AuthenticatedAdminAssessmentsRoute
  '/admin/export': typeof AuthenticatedAdminExportRoute
  '/admin/managers': typeof AuthenticatedAdminManagersRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/validations': typeof AuthenticatedAdminValidationsRoute
  '/doctor/download': typeof AuthenticatedDoctorDownloadRoute
  '/doctor/history': typeof AuthenticatedDoctorHistoryRoute
  '/doctor/new': typeof AuthenticatedDoctorNewRoute
  '/doctor/profile': typeof AuthenticatedDoctorProfileRoute
  '/mm/analytics': typeof AuthenticatedMmAnalyticsRoute
  '/mm/doctors': typeof AuthenticatedMmDoctorsRoute
  '/mm/usage': typeof AuthenticatedMmUsageRoute
  '/api/public/demo-setup': typeof ApiPublicDemoSetupRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/doctor/': typeof AuthenticatedDoctorIndexRoute
  '/mm/': typeof AuthenticatedMmIndexRoute
  '/admin/companies/$id': typeof AuthenticatedAdminCompaniesIdRoute
  '/admin/doctors/$id': typeof AuthenticatedAdminDoctorsIdRoute
  '/admin/reports/$id': typeof AuthenticatedAdminReportsIdRoute
  '/doctor/reports/$id': typeof AuthenticatedDoctorReportsIdRoute
  '/admin/companies/': typeof AuthenticatedAdminCompaniesIndexRoute
  '/admin/doctors/': typeof AuthenticatedAdminDoctorsIndexRoute
  '/admin/reports/': typeof AuthenticatedAdminReportsIndexRoute
  '/doctor/reports/': typeof AuthenticatedDoctorReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blocked': typeof BlockedRoute
  '/login': typeof LoginRoute
  '/request-demo': typeof RequestDemoRoute
  '/admin/analyses': typeof AuthenticatedAdminAnalysesRoute
  '/admin/assessments': typeof AuthenticatedAdminAssessmentsRoute
  '/admin/export': typeof AuthenticatedAdminExportRoute
  '/admin/managers': typeof AuthenticatedAdminManagersRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/validations': typeof AuthenticatedAdminValidationsRoute
  '/doctor/download': typeof AuthenticatedDoctorDownloadRoute
  '/doctor/history': typeof AuthenticatedDoctorHistoryRoute
  '/doctor/new': typeof AuthenticatedDoctorNewRoute
  '/doctor/profile': typeof AuthenticatedDoctorProfileRoute
  '/mm/analytics': typeof AuthenticatedMmAnalyticsRoute
  '/mm/doctors': typeof AuthenticatedMmDoctorsRoute
  '/mm/usage': typeof AuthenticatedMmUsageRoute
  '/api/public/demo-setup': typeof ApiPublicDemoSetupRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/doctor': typeof AuthenticatedDoctorIndexRoute
  '/mm': typeof AuthenticatedMmIndexRoute
  '/admin/companies/$id': typeof AuthenticatedAdminCompaniesIdRoute
  '/admin/doctors/$id': typeof AuthenticatedAdminDoctorsIdRoute
  '/admin/reports/$id': typeof AuthenticatedAdminReportsIdRoute
  '/doctor/reports/$id': typeof AuthenticatedDoctorReportsIdRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesIndexRoute
  '/admin/doctors': typeof AuthenticatedAdminDoctorsIndexRoute
  '/admin/reports': typeof AuthenticatedAdminReportsIndexRoute
  '/doctor/reports': typeof AuthenticatedDoctorReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/blocked': typeof BlockedRoute
  '/login': typeof LoginRoute
  '/request-demo': typeof RequestDemoRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/doctor': typeof AuthenticatedDoctorRouteRouteWithChildren
  '/_authenticated/mm': typeof AuthenticatedMmRouteRouteWithChildren
  '/_authenticated/admin/analyses': typeof AuthenticatedAdminAnalysesRoute
  '/_authenticated/admin/assessments': typeof AuthenticatedAdminAssessmentsRoute
  '/_authenticated/admin/export': typeof AuthenticatedAdminExportRoute
  '/_authenticated/admin/managers': typeof AuthenticatedAdminManagersRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/validations': typeof AuthenticatedAdminValidationsRoute
  '/_authenticated/doctor/download': typeof AuthenticatedDoctorDownloadRoute
  '/_authenticated/doctor/history': typeof AuthenticatedDoctorHistoryRoute
  '/_authenticated/doctor/new': typeof AuthenticatedDoctorNewRoute
  '/_authenticated/doctor/profile': typeof AuthenticatedDoctorProfileRoute
  '/_authenticated/mm/analytics': typeof AuthenticatedMmAnalyticsRoute
  '/_authenticated/mm/doctors': typeof AuthenticatedMmDoctorsRoute
  '/_authenticated/mm/usage': typeof AuthenticatedMmUsageRoute
  '/api/public/demo-setup': typeof ApiPublicDemoSetupRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/doctor/': typeof AuthenticatedDoctorIndexRoute
  '/_authenticated/mm/': typeof AuthenticatedMmIndexRoute
  '/_authenticated/admin/companies/$id': typeof AuthenticatedAdminCompaniesIdRoute
  '/_authenticated/admin/doctors/$id': typeof AuthenticatedAdminDoctorsIdRoute
  '/_authenticated/admin/reports/$id': typeof AuthenticatedAdminReportsIdRoute
  '/_authenticated/doctor/reports/$id': typeof AuthenticatedDoctorReportsIdRoute
  '/_authenticated/admin/companies/': typeof AuthenticatedAdminCompaniesIndexRoute
  '/_authenticated/admin/doctors/': typeof AuthenticatedAdminDoctorsIndexRoute
  '/_authenticated/admin/reports/': typeof AuthenticatedAdminReportsIndexRoute
  '/_authenticated/doctor/reports/': typeof AuthenticatedDoctorReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/blocked'
    | '/login'
    | '/request-demo'
    | '/admin'
    | '/doctor'
    | '/mm'
    | '/admin/analyses'
    | '/admin/assessments'
    | '/admin/export'
    | '/admin/managers'
    | '/admin/settings'
    | '/admin/validations'
    | '/doctor/download'
    | '/doctor/history'
    | '/doctor/new'
    | '/doctor/profile'
    | '/mm/analytics'
    | '/mm/doctors'
    | '/mm/usage'
    | '/api/public/demo-setup'
    | '/admin/'
    | '/doctor/'
    | '/mm/'
    | '/admin/companies/$id'
    | '/admin/doctors/$id'
    | '/admin/reports/$id'
    | '/doctor/reports/$id'
    | '/admin/companies/'
    | '/admin/doctors/'
    | '/admin/reports/'
    | '/doctor/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blocked'
    | '/login'
    | '/request-demo'
    | '/admin/analyses'
    | '/admin/assessments'
    | '/admin/export'
    | '/admin/managers'
    | '/admin/settings'
    | '/admin/validations'
    | '/doctor/download'
    | '/doctor/history'
    | '/doctor/new'
    | '/doctor/profile'
    | '/mm/analytics'
    | '/mm/doctors'
    | '/mm/usage'
    | '/api/public/demo-setup'
    | '/admin'
    | '/doctor'
    | '/mm'
    | '/admin/companies/$id'
    | '/admin/doctors/$id'
    | '/admin/reports/$id'
    | '/doctor/reports/$id'
    | '/admin/companies'
    | '/admin/doctors'
    | '/admin/reports'
    | '/doctor/reports'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/blocked'
    | '/login'
    | '/request-demo'
    | '/_authenticated/admin'
    | '/_authenticated/doctor'
    | '/_authenticated/mm'
    | '/_authenticated/admin/analyses'
    | '/_authenticated/admin/assessments'
    | '/_authenticated/admin/export'
    | '/_authenticated/admin/managers'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/validations'
    | '/_authenticated/doctor/download'
    | '/_authenticated/doctor/history'
    | '/_authenticated/doctor/new'
    | '/_authenticated/doctor/profile'
    | '/_authenticated/mm/analytics'
    | '/_authenticated/mm/doctors'
    | '/_authenticated/mm/usage'
    | '/api/public/demo-setup'
    | '/_authenticated/admin/'
    | '/_authenticated/doctor/'
    | '/_authenticated/mm/'
    | '/_authenticated/admin/companies/$id'
    | '/_authenticated/admin/doctors/$id'
    | '/_authenticated/admin/reports/$id'
    | '/_authenticated/doctor/reports/$id'
    | '/_authenticated/admin/companies/'
    | '/_authenticated/admin/doctors/'
    | '/_authenticated/admin/reports/'
    | '/_authenticated/doctor/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlockedRoute: typeof BlockedRoute
  LoginRoute: typeof LoginRoute
  RequestDemoRoute: typeof RequestDemoRoute
  ApiPublicDemoSetupRoute: typeof ApiPublicDemoSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocked': {
      id: '/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof BlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-demo': {
      id: '/request-demo'
      path: '/request-demo'
      fullPath: '/request-demo'
      preLoaderRoute: typeof RequestDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor': {
      id: '/_authenticated/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof AuthenticatedDoctorRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mm': {
      id: '/_authenticated/mm'
      path: '/mm'
      fullPath: '/mm'
      preLoaderRoute: typeof AuthenticatedMmRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/analyses': {
      id: '/_authenticated/admin/analyses'
      path: '/analyses'
      fullPath: '/admin/analyses'
      preLoaderRoute: typeof AuthenticatedAdminAnalysesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/assessments': {
      id: '/_authenticated/admin/assessments'
      path: '/assessments'
      fullPath: '/admin/assessments'
      preLoaderRoute: typeof AuthenticatedAdminAssessmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/export': {
      id: '/_authenticated/admin/export'
      path: '/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof AuthenticatedAdminExportRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/managers': {
      id: '/_authenticated/admin/managers'
      path: '/managers'
      fullPath: '/admin/managers'
      preLoaderRoute: typeof AuthenticatedAdminManagersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/validations': {
      id: '/_authenticated/admin/validations'
      path: '/validations'
      fullPath: '/admin/validations'
      preLoaderRoute: typeof AuthenticatedAdminValidationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/doctor/': {
      id: '/_authenticated/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof AuthenticatedDoctorIndexRouteImport
      parentRoute: typeof AuthenticatedDoctorRouteRoute
    }
    '/_authenticated/doctor/download': {
      id: '/_authenticated/doctor/download'
      path: '/download'
      fullPath: '/doctor/download'
      preLoaderRoute: typeof AuthenticatedDoctorDownloadRouteImport
      parentRoute: typeof AuthenticatedDoctorRouteRoute
    }
    '/_authenticated/doctor/history': {
      id: '/_authenticated/doctor/history'
      path: '/history'
      fullPath: '/doctor/history'
      preLoaderRoute: typeof AuthenticatedDoctorHistoryRouteImport
      parentRoute: typeof AuthenticatedDoctorRouteRoute
    }
    '/_authenticated/doctor/new': {
      id: '/_authenticated/doctor/new'
      path: '/new'
      fullPath: '/doctor/new'
      preLoaderRoute: typeof AuthenticatedDoctorNewRouteImport
      parentRoute: typeof AuthenticatedDoctorRouteRoute
    }
    '/_authenticated/doctor/profile': {
      id: '/_authenticated/doctor/profile'
      path: '/profile'
      fullPath: '/doctor/profile'
      preLoaderRoute: typeof AuthenticatedDoctorProfileRouteImport
      parentRoute: typeof AuthenticatedDoctorRouteRoute
    }
    '/_authenticated/mm/': {
      id: '/_authenticated/mm/'
      path: '/'
      fullPath: '/mm/'
      preLoaderRoute: typeof AuthenticatedMmIndexRouteImport
      parentRoute: typeof AuthenticatedMmRouteRoute
    }
    '/_authenticated/mm/analytics': {
      id: '/_authenticated/mm/analytics'
      path: '/analytics'
      fullPath: '/mm/analytics'
      preLoaderRoute: typeof AuthenticatedMmAnalyticsRouteImport
      parentRoute: typeof AuthenticatedMmRouteRoute
    }
    '/_authenticated/mm/doctors': {
      id: '/_authenticated/mm/doctors'
      path: '/doctors'
      fullPath: '/mm/doctors'
      preLoaderRoute: typeof AuthenticatedMmDoctorsRouteImport
      parentRoute: typeof AuthenticatedMmRouteRoute
    }
    '/_authenticated/mm/usage': {
      id: '/_authenticated/mm/usage'
      path: '/usage'
      fullPath: '/mm/usage'
      preLoaderRoute: typeof AuthenticatedMmUsageRouteImport
      parentRoute: typeof AuthenticatedMmRouteRoute
    }
    '/api/public/demo-setup': {
      id: '/api/public/demo-setup'
      path: '/api/public/demo-setup'
      fullPath: '/api/public/demo-setup'
      preLoaderRoute: typeof ApiPublicDemoSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/companies/': {
      id: '/_authenticated/admin/companies/'
      path: '/companies'
      fullPath: '/admin/companies/'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/companies/$id': {
      id: '/_authenticated/admin/companies/$id'
      path: '/companies/$id'
      fullPath: '/admin/companies/$id'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/doctors/': {
      id: '/_authenticated/admin/doctors/'
      path: '/doctors'
      fullPath: '/admin/doctors/'
      preLoaderRoute: typeof AuthenticatedAdminDoctorsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/doctors/$id': {
      id: '/_authenticated/admin/doctors/$id'
      path: '/doctors/$id'
      fullPath: '/admin/doctors/$id'
      preLoaderRoute: typeof AuthenticatedAdminDoctorsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reports/': {
      id: '/_authenticated/admin/reports/'
      path: '/reports'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof AuthenticatedAdminReportsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reports/$id': {
      id: '/_authenticated/admin/reports/$id'
      path: '/reports/$id'
      fullPath: '/admin/reports/$id'
      preLoaderRoute: typeof AuthenticatedAdminReportsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/doctor/reports/': {
      id: '/_authenticated/doctor/reports/'
      path: '/reports'
      fullPath: '/doctor/reports/'
      preLoaderRoute: typeof AuthenticatedDoctorReportsIndexRouteImport
      parentRoute: typeof AuthenticatedDoctorRouteRoute
    }
    '/_authenticated/doctor/reports/$id': {
      id: '/_authenticated/doctor/reports/$id'
      path: '/reports/$id'
      fullPath: '/doctor/reports/$id'
      preLoaderRoute: typeof AuthenticatedDoctorReportsIdRouteImport
      parentRoute: typeof AuthenticatedDoctorRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAnalysesRoute: typeof AuthenticatedAdminAnalysesRoute
  AuthenticatedAdminAssessmentsRoute: typeof AuthenticatedAdminAssessmentsRoute
  AuthenticatedAdminExportRoute: typeof AuthenticatedAdminExportRoute
  AuthenticatedAdminManagersRoute: typeof AuthenticatedAdminManagersRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminValidationsRoute: typeof AuthenticatedAdminValidationsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCompaniesIdRoute: typeof AuthenticatedAdminCompaniesIdRoute
  AuthenticatedAdminDoctorsIdRoute: typeof AuthenticatedAdminDoctorsIdRoute
  AuthenticatedAdminReportsIdRoute: typeof AuthenticatedAdminReportsIdRoute
  AuthenticatedAdminCompaniesIndexRoute: typeof AuthenticatedAdminCompaniesIndexRoute
  AuthenticatedAdminDoctorsIndexRoute: typeof AuthenticatedAdminDoctorsIndexRoute
  AuthenticatedAdminReportsIndexRoute: typeof AuthenticatedAdminReportsIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAnalysesRoute: AuthenticatedAdminAnalysesRoute,
    AuthenticatedAdminAssessmentsRoute: AuthenticatedAdminAssessmentsRoute,
    AuthenticatedAdminExportRoute: AuthenticatedAdminExportRoute,
    AuthenticatedAdminManagersRoute: AuthenticatedAdminManagersRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminValidationsRoute: AuthenticatedAdminValidationsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminCompaniesIdRoute: AuthenticatedAdminCompaniesIdRoute,
    AuthenticatedAdminDoctorsIdRoute: AuthenticatedAdminDoctorsIdRoute,
    AuthenticatedAdminReportsIdRoute: AuthenticatedAdminReportsIdRoute,
    AuthenticatedAdminCompaniesIndexRoute:
      AuthenticatedAdminCompaniesIndexRoute,
    AuthenticatedAdminDoctorsIndexRoute: AuthenticatedAdminDoctorsIndexRoute,
    AuthenticatedAdminReportsIndexRoute: AuthenticatedAdminReportsIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedDoctorRouteRouteChildren {
  AuthenticatedDoctorDownloadRoute: typeof AuthenticatedDoctorDownloadRoute
  AuthenticatedDoctorHistoryRoute: typeof AuthenticatedDoctorHistoryRoute
  AuthenticatedDoctorNewRoute: typeof AuthenticatedDoctorNewRoute
  AuthenticatedDoctorProfileRoute: typeof AuthenticatedDoctorProfileRoute
  AuthenticatedDoctorIndexRoute: typeof AuthenticatedDoctorIndexRoute
  AuthenticatedDoctorReportsIdRoute: typeof AuthenticatedDoctorReportsIdRoute
  AuthenticatedDoctorReportsIndexRoute: typeof AuthenticatedDoctorReportsIndexRoute
}

const AuthenticatedDoctorRouteRouteChildren: AuthenticatedDoctorRouteRouteChildren =
  {
    AuthenticatedDoctorDownloadRoute: AuthenticatedDoctorDownloadRoute,
    AuthenticatedDoctorHistoryRoute: AuthenticatedDoctorHistoryRoute,
    AuthenticatedDoctorNewRoute: AuthenticatedDoctorNewRoute,
    AuthenticatedDoctorProfileRoute: AuthenticatedDoctorProfileRoute,
    AuthenticatedDoctorIndexRoute: AuthenticatedDoctorIndexRoute,
    AuthenticatedDoctorReportsIdRoute: AuthenticatedDoctorReportsIdRoute,
    AuthenticatedDoctorReportsIndexRoute: AuthenticatedDoctorReportsIndexRoute,
  }

const AuthenticatedDoctorRouteRouteWithChildren =
  AuthenticatedDoctorRouteRoute._addFileChildren(
    AuthenticatedDoctorRouteRouteChildren,
  )

interface AuthenticatedMmRouteRouteChildren {
  AuthenticatedMmAnalyticsRoute: typeof AuthenticatedMmAnalyticsRoute
  AuthenticatedMmDoctorsRoute: typeof AuthenticatedMmDoctorsRoute
  AuthenticatedMmUsageRoute: typeof AuthenticatedMmUsageRoute
  AuthenticatedMmIndexRoute: typeof AuthenticatedMmIndexRoute
}

const AuthenticatedMmRouteRouteChildren: AuthenticatedMmRouteRouteChildren = {
  AuthenticatedMmAnalyticsRoute: AuthenticatedMmAnalyticsRoute,
  AuthenticatedMmDoctorsRoute: AuthenticatedMmDoctorsRoute,
  AuthenticatedMmUsageRoute: AuthenticatedMmUsageRoute,
  AuthenticatedMmIndexRoute: AuthenticatedMmIndexRoute,
}

const AuthenticatedMmRouteRouteWithChildren =
  AuthenticatedMmRouteRoute._addFileChildren(AuthenticatedMmRouteRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDoctorRouteRoute: typeof AuthenticatedDoctorRouteRouteWithChildren
  AuthenticatedMmRouteRoute: typeof AuthenticatedMmRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDoctorRouteRoute: AuthenticatedDoctorRouteRouteWithChildren,
  AuthenticatedMmRouteRoute: AuthenticatedMmRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BlockedRoute: BlockedRoute,
  LoginRoute: LoginRoute,
  RequestDemoRoute: RequestDemoRoute,
  ApiPublicDemoSetupRoute: ApiPublicDemoSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
